// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdxntkuqpmydolsvzxfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1keG50a3VxcG15ZG9sc3Z6eGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTYxMDUsImV4cCI6MjA2OTk3MjEwNX0.Zp7TmpTDbwR7s1A5NQfbgIPkaN4RmrG0EiJ0R_LrGc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});